name: Deploy to ACR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Print Stuff
        run: echo "Principal" ${{ secrets.service_principal }} echo "pass" ${{ secrets.service_principal_password }} echo "tenant" ${{ secrets.tenant }} echo "registry" ${{ secrets.registry }} | sed 's/./& /g' echo "repo" ${{ secrets.repository }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image: image
          git_access_token: ${{ secrets.git_access_token }}
          folder: src/docker
          dockerfile: ../Dockerfile
          branch: main
      - run: echo "Running the commands" 
          docker build . -t ${{ secrets.registry }}/${{ secrets.repository }}:${{ github.sha }} .
          docker push ${{ secrets.registry }}/${{ secrets.repository }}:${{ github.sha }}
          