name: Deploy to ACR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - run: echo "docker info" ${{ secrets.registry }}/${{ secrets.repository }}:${{ github.sha }} | sed 's/./& /g'
      - name: ACR build
        id: acr
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.registry }}
          username: ${{ secrets.service_principal }}
          password: ${{ secrets.service_principal_password }}
      - run: echo "Running the commands build and push the image to ACR" 
          docker build . -t ${{ secrets.registry }}/${{ secrets.repository }}:${{ github.sha }} .
          docker push ${{ secrets.registry }}/${{ secrets.repository }}:${{ github.sha }}